default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV.fetch("DATABASE_URL", "") %>
  host: <%= ENV.fetch("DATABASE_HOST", "") %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "") %>

development:
  <<: *default
  database: simple_group_development

test:
  <<: *default
  database: simple_group_test

production:
  <<: *default
